### ISSUE TITLE
Remove namespace

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/to-milliseconds#4]
It sucks.

Request [https://npmjs.com/to-milliseconds](https://npmjs.com/to-milliseconds)'s author to transfer ownership.

**Comment by stevenvachon** [comment]
@dslaugh ^^

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Comment by stevenvachon** [comment]
?

**Comment by stevenvachon** [comment]
@dslaugh ^^
